name: ohdate_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dob_input_field: ^2.0.0
  intl: 0.18.1
  firebase_auth: ^4.17.7
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  firebase_core: ^2.26.0
  cloud_firestore: ^4.15.7

flutter:
  uses-material-design: true
  assets:
    - lib/imatges/

