name: ohdate_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dob_input_field: ^2.0.0
  intl: ^0.19.0
  firebase_auth: ^4.17.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  firebase_core: ^1.10.6
  cloud_firestore: ^3.1.6

flutter:
  uses-material-design: true
  assets:
    - lib/imatges/

